"""add more transaction fields

Revision ID: ad00894d5666
Revises: c1d7b3166531
Create Date: 2026-02-04 00:55:32.007465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad00894d5666'
down_revision: Union[str, None] = 'c1d7b3166531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('alias_name', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('alias_iban', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('sub_type', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('geo_latitude', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('geo_longitude', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('batch_id', sa.BigInteger(), nullable=True))
    op.add_column('transactions', sa.Column('scheduled_id', sa.BigInteger(), nullable=True))
    op.add_column('transactions', sa.Column('request_reference_split_the_bill', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'request_reference_split_the_bill')
    op.drop_column('transactions', 'scheduled_id')
    op.drop_column('transactions', 'batch_id')
    op.drop_column('transactions', 'geo_longitude')
    op.drop_column('transactions', 'geo_latitude')
    op.drop_column('transactions', 'balance_after')
    op.drop_column('transactions', 'sub_type')
    op.drop_column('transactions', 'alias_iban')
    op.drop_column('transactions', 'alias_name')
    # ### end Alembic commands ###
