"""add sender receiver fields

Revision ID: ccd7574f5b47
Revises: ad00894d5666
Create Date: 2026-02-04 01:00:36.834525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd7574f5b47'
down_revision: Union[str, None] = 'ad00894d5666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('sender_iban', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('receiver_name', sa.String(length=255), nullable=True))
    op.add_column('transactions', sa.Column('receiver_iban', sa.String(length=50), nullable=True))
    op.drop_column('transactions', 'alias_iban')
    op.drop_column('transactions', 'alias_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('alias_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('alias_iban', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'receiver_iban')
    op.drop_column('transactions', 'receiver_name')
    op.drop_column('transactions', 'sender_iban')
    op.drop_column('transactions', 'sender_name')
    # ### end Alembic commands ###
