"""'add raw_json column to transactions'

Revision ID: d66ad6e7602e
Revises: 2d9ebf21f237
Create Date: 2026-02-04 08:16:55.951393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66ad6e7602e'
down_revision: Union[str, None] = '2d9ebf21f237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
